name: 'Dispatch CentOS 7 Verify'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_trigger-centos7-verify.yml'

permissions:
  actions: write
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Dispatch CentOS 7 Verify'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run centos7-verify.yml --repo "$GITHUB_REPOSITORY" --ref main
